using System;

// <auto-generated>
// This file was generated by SplitCS on 2025-11-06 12:09:45
// Changes to this file may be lost if the code is regenerated.
// </auto-generated>

namespace TestNamespace;

public partial class SampleClass
{
    }

    private void ValidateAge(int age)
    {
    if (age < 0)
    throw new ArgumentException("Age cannot be negative");
    }

    throw new ArgumentException("Age cannot be negative");
    }

    private void ValidateName(string name)
    {
    if (string.IsNullOrWhiteSpace(name))
    throw new ArgumentException("Name cannot be empty");
    }

    throw new ArgumentException("Name cannot be empty");
    }

    private string FormatName(string name)
    {
    return name.Trim().ToTitleCase();
    }
}
