using System;

// <auto-generated>
// This file was generated by SplitCS on 2025-11-06 12:09:45
// Changes to this file may be lost if the code is regenerated.
// </auto-generated>

namespace TestNamespace;

public partial class SampleClass
{
    private int _age;

    public SampleClass(string name, int age)
    {
    _name = name;
    _age = age;
    }

    }

    public string Name
    {
    get { return _name; }
    set { _name = value; }
    }

    }

    public int Age
    {
    get { return _age; }
    set { _age = value; }
    }

    }

    public void DisplayInfo()
    {
    Console.WriteLine($"Name: {_name}, Age: {_age}");
    }

    }

    public string GetFullInfo()
    {
    return $"Person: {_name} ({_age} years old)";
    }

    }

    public static SampleClass CreateDefault()
    {
    return new SampleClass("Unknown", 0);
    }
}
