using System;

// <auto-generated>
// This file was generated by SplitCS on 2025-11-06 12:09:45
// Changes to this file may be lost if the code is regenerated.
// </auto-generated>

namespace TestNamespace;

public static partial class StringExtensions
{
    {
    public static string ToTitleCase(this string input)
    {
    if (string.IsNullOrEmpty(input))
    return input;

    return char.ToUpper(input[0]) + input.Substring(1).ToLower();
    }
}
